var bd = $("body");




$(document).ready(function () {
    var bodySt = bd.html();

    if (bodySt.indexOf("somee") != -1) {
        var fi = bodySt.indexOf("<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->");
        var la = fi + bodySt.substring(fi + "<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->".length, bodySt.length).indexOf("<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->");
        if (fi != -1) {
            var block = bodySt.substr(fi, la - (fi - ("<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->".length * 2)));
            if (bodySt.indexOf("<center") != -1) bodySt = bodySt.replace(bodySt.sub(bodySt.indexOf("<center"), bodySt.indexOf("</center>")), "");
            bodySt = bodySt.replace(block, "");
            bodySt = bodySt.replace("http://ads.mgmt.somee.com/serveimages/ad2/WholeInsert4.js?_=1363873986974", "");
            bd.html(bodySt);
        }
    }
});